swagger: "2.0"
info:
  title: News API
  version: 1.0.0
  description: API for managing news articles
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /news:
    get:
      summary: Get a list of all news
      description: Returns a paginated list of news articles
      parameters:
        - name: page
          in: query
          description: Page number of the results
          type: integer
          default: 0
        - name: size
          in: query
          description: Number of items per page
          type: integer
          default: 10
        - name: sort
          in: query
          description: Sort field
          type: string
          default: title
        - name: direction
          in: query
          description: Sort direction
          type: string
          default: asc
      responses:
        '200':
          description: Successfully retrieved the list of news
          schema:
            type: object
            properties:
              content:
                type: array
                items:
                  $ref: '#/definitions/NewsDtoResponse'
              totalPages:
                type: integer
              totalElements:
                type: integer
              last:
                type: boolean
              first:
                type: boolean
              numberOfElements:
                type: integer
              size:
                type: integer
              number:
                type: integer
        '500':
          description: Internal server error
    post:
      summary: Create a new news article
      description: Creates a new news article with the given request body
      parameters:
        - in: body
          name: body
          description: News data
          required: true
          schema:
            $ref: '#/definitions/NewsDtoRequest'
      responses:
        '201':
          description: Successfully created a new news
          schema:
            $ref: '#/definitions/NewsDtoResponse'
        '400':
          description: Invalid news data
        '500':
          description: Internal server error
  /news/{id}:
    get:
      summary: Get a news article by ID
      description: Returns the news article with the specified ID
      parameters:
        - name: id
          in: path
          description: News ID
          required: true
          type: integer
      responses:
        '200':
          description: Successfully retrieved the news article
          schema:
            $ref: '#/definitions/NewsDtoResponse'
        '404':
          description: News not found
    put:
      summary: Update a news article
      description: Updates the news article with the specified ID
      parameters:
        - name: id
          in: path
          description: News ID
          required: true
          type: integer
        - in: body
          name: body
          description: Updated news data
          required: true
          schema:
            $ref: '#/definitions/NewsDtoRequest'
      responses:
        '200':
          description: Successfully updated the news article
          schema:
            $ref: '#/definitions/NewsDtoResponse'
        '400':
          description: Invalid news data
        '404':
          description: News not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a news article by ID
      description: Deletes the news article with the specified ID
      parameters:
        - name: id
          in: path
          description: News ID
